# Generated by Django 4.0.5 on 2022-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(default=0)),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('phone', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=255)),
                ('res_step', models.IntegerField(default=0)),
            ],
        ),
    ]
