# Generated by Django 4.0.5 on 2022-12-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='familiya',
        ),
    ]
