# Generated by Django 4.0.5 on 2022-12-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_foydalanuvchi_familiya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='ism',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
