# Generated by Django 4.0.5 on 2022-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_foydalanuvchi_city_alter_foydalanuvchi_ism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='ecoin',
            field=models.IntegerField(default=0),
        ),
    ]
