# Generated by Django 4.0.5 on 2022-12-18 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_foydalanuvchi_ecoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='add',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('tasdiq', models.BooleanField(default=False)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='web.foydalanuvchi')),
            ],
        ),
    ]
