# Generated by Django 4.0.5 on 2022-12-20 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_foydalanuvchi_add_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(editable=False),
        ),
    ]
